const CARDS = [
  { issuer: 'Apple',   card: 'Apple',                  type: 'Personal', retention: 'Yes',   annualFee: 0,   opened: '08/12/2019', pc: '-',          from: '-' },
  { issuer: 'Chase',   card: 'Freedom Unlimited',      type: 'Personal', retention: 'Yes',   annualFee: 0,   opened: '03/16/2024', pc: '01/19/2026', from: 'Sapphire' },
  { issuer: 'Amex',    card: 'Delta Reserve',          type: 'Personal', retention: 'Yes',   annualFee: 650, opened: '03/24/2024', pc: '03/09/2025', from: 'Delta Blue' },
  { issuer: 'Amex',    card: 'Platinum',               type: 'Personal', retention: 'Yes',   annualFee: 895, opened: '04/02/2024', pc: '-',          from: '-' },
  { issuer: 'Amex',    card: 'BBP',                    type: 'Business', retention: 'Yes',   annualFee: 0,   opened: '06/07/2024', pc: '-',          from: '-' },
  { issuer: 'Amex',    card: 'Delta Business Reserve', type: 'Business', retention: 'Yes',   annualFee: 650, opened: '06/24/2024', pc: '01/25/2025', from: 'Delta Biz Gold' },
  { issuer: 'Amex',    card: 'Hilton Honors Business', type: 'Business', retention: 'Yes',   annualFee: 195, opened: '04/26/2025', pc: '-',          from: '-' },
  { issuer: 'Chase',   card: 'IHG Premier',            type: 'Personal', retention: 'Yes',   annualFee: 99,  opened: '06/02/2025', pc: '-',          from: '-' },
  { issuer: 'USB',     card: 'Shopper Cash',           type: 'Personal', retention: 'No',    annualFee: 95,  opened: '07/17/2025', pc: '-',          from: '-' },
  { issuer: 'USB',     card: 'Cash+',                  type: 'Personal', retention: 'No',    annualFee: 0,   opened: '07/17/2025', pc: '-',          from: '-' },
  { issuer: 'Amex',    card: 'Green',                  type: 'Personal', retention: 'Yes',   annualFee: 150, opened: '09/18/2025', pc: '-',          from: '-' },
  { issuer: 'Imprint', card: 'Rakuten',                type: 'Personal', retention: 'Yes',   annualFee: 0,   opened: '10/23/2025', pc: '-',          from: '-' },
  { issuer: 'Bilt',    card: 'Palladium',              type: 'Personal', retention: 'No',    annualFee: 495, opened: '01/22/2026', pc: '-',          from: '-' },
  { issuer: 'Amex',    card: 'Gold',                   type: 'Personal', retention: 'Maybe', annualFee: 325, opened: '02/08/2026', pc: '-',          from: '-' },
  { issuer: 'TD Bank', card: 'Cash',                   type: 'Personal', retention: 'Yes',   annualFee: 0,   opened: '04/01/2026', pc: '-',          from: '-' },
  { issuer: 'FNBO',    card: 'Amtrak',                 type: 'Personal', retention: 'Yes',   annualFee: 99,  opened: '04/14/2026', pc: '-',          from: '-' },
  { issuer: 'Bread',   card: 'AAA Daily Advantage',    type: 'Personal', retention: 'Maybe', annualFee: 0,   opened: '04/21/2026', pc: '-',          from: '-' },
  { issuer: 'TD Bank', card: 'Double Up',              type: 'Personal', retention: 'Yes',   annualFee: 0,   opened: '04/24/2026', pc: '-',          from: '-' },
];
