const CARDS = [
  {
    issuer: 'Goldman Sachs', card: 'Apple', type: 'Personal', retention: 'Yes', annualFee: 0, opened: '08/12/2019',
    network: 'Mastercard',
    earns: ['3% Apple purchases', '2% Apple Pay', '1% on everything'],
    perks: ['Daily Cash', 'No fees of any kind', 'Family sharing'],
  },
  {
    issuer: 'Chase', card: 'Freedom Unlimited', type: 'Personal', retention: 'Yes', annualFee: 0, opened: '03/16/2024',
    network: 'Visa',
    earns: ['5% Chase Travel', '3% dining', '3% drugstores', '1.5% on everything'],
    perks: ['Transfer to Sapphire / Ink for UR value', 'No annual fee'],
  },
  {
    issuer: 'Amex', card: 'Delta Reserve', type: 'Personal', retention: 'Yes', annualFee: 650, opened: '03/24/2024',
    network: 'Amex',
    earns: ['3x Delta', '1x on everything'],
    perks: ['Sky Club access', 'Companion certificate (FC/PE/MC)', 'Upgrade priority', 'MQD boost'],
  },
  {
    issuer: 'Amex', card: 'Platinum', type: 'Personal', retention: 'Yes', annualFee: 895, opened: '04/02/2024',
    network: 'Amex',
    earns: ['5x flights (direct or Amex Travel)', '5x prepaid hotels (Amex Travel)'],
    perks: ['Centurion + Priority Pass lounges', '$200 hotel credit', '$200 airline incidental', '$200 Uber', '$189 Clear', 'Hotel elite status'],
  },
  {
    issuer: 'Amex', card: 'BBP', type: 'Business', retention: 'Yes', annualFee: 0, opened: '06/07/2024',
    network: 'Amex',
    earns: ['2x on everything (up to $50K/yr)', '1x after cap'],
    perks: ['No annual fee', 'Membership Rewards points', 'Pay over time'],
  },
  {
    issuer: 'Amex', card: 'Delta Business Reserve', type: 'Business', retention: 'Yes', annualFee: 650, opened: '06/24/2024',
    network: 'Amex',
    earns: ['3x Delta', '1.5x on $5K+ purchases', '1x on everything'],
    perks: ['Sky Club access', 'Companion certificate', 'MQM accelerator', 'Status boost'],
  },
  {
    issuer: 'Amex', card: 'Hilton Honors Business', type: 'Business', retention: 'Yes', annualFee: 195, opened: '04/26/2025',
    network: 'Amex',
    earns: ['12x Hilton', '6x US restaurants / gas / wireless / shipping', '4x flights / car rentals booked direct', '3x other purchases'],
    perks: ['Hilton Gold status', 'Free weekend night ($15K spend)', '10 Priority Pass visits/yr'],
  },
  {
    issuer: 'Chase', card: 'IHG Premier', type: 'Personal', retention: 'Yes', annualFee: 99, opened: '06/02/2025',
    network: 'Mastercard',
    earns: ['10x IHG', '5x travel / dining / gas', '3x on everything'],
    perks: ['Anniversary free night (≤40K)', 'IHG Platinum Elite', '4th night free on award stays'],
  },
  {
    issuer: 'US Bank', card: 'Shopper Cash', type: 'Personal', retention: 'No', annualFee: 95, opened: '07/17/2025',
    network: 'Visa',
    earns: ['6% on 2 chosen categories ($1.5K/qtr)', '3% on 1 chosen category', '5.5% travel via US Bank', '1.5% else'],
    perks: ['Customizable bonus categories', 'Quarterly bonus cap'],
  },
  {
    issuer: 'US Bank', card: 'Cash+', type: 'Personal', retention: 'No', annualFee: 0, opened: '07/17/2025',
    network: 'Visa',
    earns: ['5% on 2 chosen categories ($2K/qtr)', '2% on 1 everyday', '1% on everything'],
    perks: ['Customizable categories', 'No annual fee'],
  },
  {
    issuer: 'Amex', card: 'Green', type: 'Personal', retention: 'Yes', annualFee: 150, opened: '09/18/2025',
    network: 'Amex',
    earns: ['3x travel', '3x transit', '3x dining (worldwide)'],
    perks: ['$189 Clear credit', '$100 LoungeBuddy credit', 'No foreign tx fee'],
  },
  {
    issuer: 'Imprint', card: 'Rakuten', type: 'Personal', retention: 'Yes', annualFee: 0, opened: '10/23/2025',
    network: 'Visa',
    earns: ['10% Rakuten.com', '5% travel via Rakuten', '3% dining / groceries', '1% else'],
    perks: ['Cashback as Rakuten Cash', 'No annual fee', 'No foreign tx fee'],
  },
  {
    issuer: 'Bilt', card: 'Palladium', type: 'Personal', retention: 'No', annualFee: 495, opened: '01/22/2026',
    network: 'Mastercard',
    earns: ['2x on everything'],
    perks: [],
  },
  {
    issuer: 'Amex', card: 'Gold', type: 'Personal', retention: 'Maybe', annualFee: 325, opened: '02/08/2026',
    network: 'Amex',
    earns: ['4x dining (worldwide)', '4x US groceries ($25K cap)', '3x flights (direct or Amex Travel)'],
    perks: ['$120 dining credit ($10/mo)', '$120 Uber Cash', '$100 resort credit', 'No foreign tx fee'],
  },
  {
    issuer: 'TD Bank', card: 'Cash', type: 'Personal', retention: 'Yes', annualFee: 0, opened: '04/01/2026',
    network: 'Visa',
    earns: ['3% dining', '2% groceries', '1% on everything'],
    perks: ['No annual fee', 'Choose your top categories'],
  },
  {
    issuer: 'FNBO', card: 'Amtrak', type: 'Personal', retention: 'Yes', annualFee: 99, opened: '04/14/2026',
    network: 'Mastercard',
    earns: ['3x Amtrak', '2x dining / transit / rideshare', '1x on everything'],
    perks: ['20K bonus points yearly', 'Status boost', 'Companion coupon', '$100 station lounge'],
  },
  {
    issuer: 'Bread', card: 'AAA Daily Advantage', type: 'Personal', retention: 'Maybe', annualFee: 0, opened: '04/21/2026',
    network: 'Mastercard',
    earns: ['5% groceries (up to $10K/yr)', '3% gas / wholesale clubs', '1% on everything'],
    perks: ['No annual fee', 'AAA member benefits', 'No FTF'],
  },
  {
    issuer: 'TD Bank', card: 'Double Up', type: 'Personal', retention: 'Yes', annualFee: 0, opened: '04/24/2026',
    network: 'Visa',
    earns: ['2% on everything (1% earn + 1% on redemption)'],
    perks: ['No annual fee', 'Simple flat-rate cashback'],
  },
];
